### ISSUE TITLE
Cannot find module 'next-sanity' or its corresponding type declarations.

### ISSUE THREAD

**Issue by crazycodestar** [sanity-io/next-sanity#1656]
All I've done is follow the installation guide to integrate sanity into Nextjs `npx create sanity@latest`. But when I go to the `client.ts` file. it shows an error `Cannot find module 'next-sanity' or its corresponding type declarations.` on the `import { createClient } from "next-sanity"`.

Edit: I should also not that it would work like the package is still installed, if anyone was wondering

**Comment by patrickaigbogun** [comment]
This is a serious issue with the nextjs integration, i have been battling with it as well for the past 10hours, the solution is to move your sanity.config.* file into your sanity folder and switch all imports to sanity for piece of mind. essentially do not use next-sanity

**Comment by stipsan** [comment]
Hi, in order to help you we need you to provide a link to a github repository that demonstrates the problem.
You may fork [one](https://github.com/sanity-io/template-nextjs-personal-website?tab=readme-ov-file) [of](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3) [our](https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website) [templates](https://www.sanity.io/exchange/type=templates/framework=nextjs) and alter it until it reproduces the problem.
Once you have that create a new issue and we'll jump right in and be able to assist.
Thanks!
