### ISSUE TITLE
User authentication in NextJs 13.

### ISSUE THREAD

**Issue by Php93** [sanity-io/next-sanity#277]
I created a blog using sanity. 
Now I want to create a user registration and like system (user can like a post and it will be saved). Can I do it with sanity? 

I thought to create a schema for user, and then just add the liked posts to the array.

**Comment by stipsan** [comment]
Hey @Php93, this is possible to do with Sanity and I suggest you ask this in our Community Slack: https://slack.sanity.io/ so that one of our Community Engineers can guide you through it :relaxedL

The team that monitors issues on this repo don't have capacity to handle general questions and focuses on feature requests and bug reports directly related to the `next-sanity` library itself. Our community Slack have a dedicated #next channel that provide you with a ton of resources and an active community that can help you build just about anything with the `Next.js + Sanity` stack 😉
