### ISSUE TITLE
Unable to deploy graphql endpoint

### ISSUE THREAD

**Issue by letsandeepio** [sanity-io/next-sanity#327]
Running the command `sanity deploy` throws up a bunch of errors `ERROR: Transforming let to the configured target environment ("es5") is not is not supported yet `

My tsconfig has set the env to es5, bumping it up to es6 then results in this error

<img width="607" alt="Screenshot 2023-02-07 at 6 29 29 AM" src="https://user-images.githubusercontent.com/48636430/217233126-0bab429d-4ea2-485b-ba2f-0dc0ea3ffa2c.png">

My sanity.cli.ts & sanity.config.ts is the root of the nextjs folder:

```
import { defineCliConfig } from 'sanity/cli';

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET

export default defineCliConfig({
  api: {
    projectId,
    dataset,
  },
});
```

**Comment by stipsan** [comment]
In order to use env vars from NextJS inside a `sanity.config.ts` you'll need to use `@next/env`:
https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/blob/9652967db1cdb44136984ad7abdecf57143e82d5/sanity.cli.ts#L1-L5

If it still doesn't work could you paste in the contents of your `tsconfig.json`?

**Comment by stipsan** [comment]
Can't reproduce
