### ISSUE TITLE
Data not refreshing when changing

### ISSUE THREAD

**Issue by abdulhadi240** [sanity-io/next-sanity#591]
Hello , I am using nextjs latest version . when I change my data from live website no changes occur but on the other hand when I change data from local host the changes can be seen . I have also tried revalidation:1 but no effect . am I missing some thing plz guide.

<img width="714" alt="Capture" src="https://github.com/sanity-io/next-sanity/assets/70109681/b37d3f64-97a6-4080-b38b-3c19f35568aa">

**Comment by Lucifer0x17** [comment]
I was facing the same issue. I downgraded the next sanity to version <code>"next-sanity": "^4.1.5",</code> 
Now it's working fine. Hoping the bug in this version will be solved soon.

**Comment by stipsan** [comment]
If you click "Purge Everything" on your Vercel Project Settings, does the changes show up afterwards?

![image](https://github.com/sanity-io/next-sanity/assets/81981/97a0facb-4a3e-4d9f-b99d-8b0280c12a7d)

**Comment by abdulhadi240** [comment]
It will then decrease the performance of my project as there will be no
backward and forward caching.

**Comment by stipsan** [comment]
@abdulhadi240 it doesn't disable caching completely, it just clears it and will fill up again. If you "Purge Everything" and see updated content, it means that things are working on our end. You'll need to open an issue at [Vercel](https://github.com/vercel/next.js) who can help you track down if this is due to a configuration in your app, or a bug in Next.js itself.
