### ISSUE TITLE
Unable to build successfully

### ISSUE THREAD

**Issue by amanuel-s-tadesse** [sanity-io/next-sanity#654]
i just cloned the project then follow the installation process after that when i try to build i got the following error
```
[warning] Error when using sourcemap for reporting an error: Can't resolve original location of error.

[warning] Entry module "src/preview/index.ts" is using named and default exports together. Consumers of your bundle will have to use `chunk.default` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning.
```

also when i try to deploy it to vercel i got the same source map issue

```
 [warning] Error when using sourcemap for reporting an error: Can't resolve original location of error.

 [warning] Error when using sourcemap for reporting an error: Can't resolve original location of error.

 Error: The file "/vercel/path0/dist/routes-manifest.json" couldn't be found. This is often caused by a misconfiguration in your project.
Learn More: https://err.sh/vercel/vercel/now-next-routes-manifest
```

**Comment by stipsan** [comment]
Hi, in order to help you we need you to provide a link to a github repository that demonstrates the problem.
You may fork [one](https://github.com/sanity-io/template-nextjs-personal-website?tab=readme-ov-file) [of](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3) [our](https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website) [templates](https://www.sanity.io/exchange/type=templates/framework=nextjs) and alter it until it reproduces the problem.
Once you have that create a new issue and we'll jump right in and be able to assist.
Thanks!
