### ISSUE TITLE
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by Chrisley304** [sanity-io/next-sanity#665]
We were using Sanity with Next `pages` routing and it was working perfectly. We migrated to `app` routing and now when we enter to `/studio` this warning appear a lot of times on the console and we can't get rid of it:
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

This is our `page.tsx` of the `studio/[[...index]]` directory:
```tsx
'use client'

/**
 * This route is responsible for the built-in authoring environment using Sanity Studio.
 * All routes under your studio path is handled by this file using Next.js' catch-all routes:
 * https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes
 *
 * You can learn more about the next-sanity package here:
 * https://github.com/sanity-io/next-sanity
 */

import { NextStudio } from 'next-sanity/studio'
import config from '../../../../../sanity.config'

export default function StudioPage() {
  return <NextStudio config={config} />
}
```

**Comment by stipsan** [comment]
Hi, in order to help you we need you to provide a link to a github repository that demonstrates the problem.
You may fork [one](https://github.com/sanity-io/template-nextjs-personal-website?tab=readme-ov-file) [of](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3) [our](https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website) [templates](https://www.sanity.io/exchange/type=templates/framework=nextjs) and alter it until it reproduces the problem.
Once you have that create a new issue and we'll jump right in and be able to assist.
Thanks!
