### ISSUE TITLE
problems upgrading to v5 – help needed – DX suggestions

### ISSUE THREAD

**Issue by felixhaeberle** [sanity-io/next-sanity#686]
Hello there, I'm currently running with **v0.8** of the `next-sanity` package & in the last 12 months there has been quite some change in this package & I can't resolve how I can properly convert this file to **v5** despite having read all the migrations. 

I'm confused by the sheer amount of migration docs available and can't map my functionality in this file properly.

```ts
import {
  createClient,
  createPreviewSubscriptionHook
} from "next-sanity";

import createImageUrlBuilder from '@sanity/image-url'
import { PortableText as PortableTextComponent } from '@portabletext/react'

import { config } from "./config";

if (!config.projectId) {
  throw Error(
    "The Project ID is not set. Check your environment variables."
  );
}
export const urlFor = source =>
  createImageUrlBuilder(config).image(source);

export const imageBuilder = source =>
  createImageUrlBuilder(config).image(source);

export const usePreviewSubscription =
  createPreviewSubscriptionHook(config);

// Set up Portable Text serialization
// export const PortableText = createPortableTextComponent({
//   ...config,
//   // Serializers passed to @sanity/block-content-to-react
//   // (https://github.com/sanity-io/block-content-to-react)
//   serializers: {
//     types: {
//       code: props => (
//         <pre data-language={props.node.language}>
//           <code>{props.node.code}</code>
//         </pre>
//       )
//     },
//   }
// });

export const PortableText = (props) => <PortableTextComponent components={{}} {...props} />

export const client = createClient(config);

export const previewClient = createClient({
  ...config,
  useCdn: false
});

export const getClient = usePreview =>
  usePreview ? previewClient : client;
export default client;
```

Can somebody help me out & guide me on how I have to change my application? For example, searching for `createPreviewSubscriptionHook` has not a single mention in the README, also other deprecated API's are not mentioned. 

It would be good DX to have a table or something where it can be easily observed what changes in which version & what are the replacements for the specific functions. Otherwise people have to dig through the docs & possibly do not find what they are searching for.

Thank you very much in advance!! 🙏

**Comment by stipsan** [comment]
Hi @felixhaeberle! 

The `createPreviewSubscriptionHook` has been replaced with two separate parts.
Your components will use `import {useLiveQuery} from 'next-sanity/preview'` instead of `usePreviewSubscription`.

And instead of calling `createPreviewSubscriptionHook` you'll setup `import {LiveQueryProvider} from 'next-sanity/preview'`.

With a longer migration path like yours perhaps it's easier to [deploy](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fsanity-io%2Ftemplate-nextjs-personal-website&project-name=personal-website-nextjs-sanity&repository-name=personal-website-nextjs-sanity&demo-title=Personal%20Website%20with%20Built-in%20Content%20Editing&demo-description=A%20Sanity-powered%20personal%20website%20with%20built-in%20content%20editing%20and%20instant%20previews.&demo-url=https%3A%2F%2Fnextjs-personal-website.sanity.build%2F&demo-image=https%3A%2F%2Fuser-images.githubusercontent.com%2F6951139%2F206395107-e58a796d-13a9-400a-94b6-31cb5df054ab.png&integration-ids=oac_hb2LITYajhRQ0i4QznmKH7gx&external-id=nextjs;template=nextjs-personal-website-cms-sanity-v3) this [template](https://github.com/sanity-io/template-nextjs-personal-website) and get familiar with how the current recommended stack works. And then start to incrementally migrate over the pieces of functionality that makes sense for your app.

And of course, feel free to post more questions here and we'll do our best to help you get migrated :)

>It would be good DX to have a table or something where it can be easily observed what changes in which version & what are the replacements for the specific functions. Otherwise people have to dig through the docs & possibly do not find what they are searching for.

Excellent feedback, thanks!

**Comment by stipsan** [comment]
Closing this assuming it's fixed. If it's still a problem feel free to create a new issue that links to this one and we'll dive back in :)
